### Запрос на загрузку данных неавторизованного пользователя
POST http://127.0.0.1:8000/import/price_import/


### Запрос на загрузку данных от покупателя
POST http://127.0.0.1:8000/import/price_import/
Content-Type: application/json
Authorization: Token 0689561118e91143de2d5d6b0917cb6b66be46b9


### Запрос на загрузку данных от менеджера поставщика
POST http://127.0.0.1:8000/import/price_import/
Content-Type: application/json
Authorization: Token 855cd926625b97870d97894ae525c5e7c646b464