# Generated by Django 4.2.2 on 2023-07-23 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ('company_name',), 'verbose_name': 'Поставщик', 'verbose_name_plural': 'Список поставщиков'},
        ),
        migrations.RenameField(
            model_name='company',
            old_name='name',
            new_name='company_name',
        ),
    ]
