# Generated by Django 4.2.2 on 2023-07-31 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0002_alter_company_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='companies',
            new_name='company',
        ),
    ]
