# Generated by Django 2.2.16 on 2023-06-06 16:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0003_auto_20230604_2128'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'Категория', 'verbose_name_plural': 'Список категорий'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ('type',), 'verbose_name': 'Контакты пользователя', 'verbose_name_plural': 'Список контактов пользователя'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-register_date',), 'verbose_name': 'Заказ', 'verbose_name_plural': 'Список заказов'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Позиция заказа', 'verbose_name_plural': 'Список позиций заказа'},
        ),
        migrations.AlterModelOptions(
            name='parameter',
            options={'ordering': ('name',), 'verbose_name': 'Параметр', 'verbose_name_plural': 'Список параметров'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',), 'verbose_name': 'Продукт', 'verbose_name_plural': 'Список продуктов'},
        ),
        migrations.AlterModelOptions(
            name='productinfo',
            options={'ordering': ('name',), 'verbose_name': 'Информация о продукте', 'verbose_name_plural': 'Информационный список о продуктах'},
        ),
        migrations.AlterModelOptions(
            name='productparameter',
            options={'ordering': ('value',), 'verbose_name': 'Параметр продукта', 'verbose_name_plural': 'Список параметров продукта'},
        ),
        migrations.AlterModelOptions(
            name='shop',
            options={'ordering': ('name',), 'verbose_name': 'Магазин', 'verbose_name_plural': 'Список магазинов'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('username',), 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Список пользователей'},
        ),
        migrations.RenameField(
            model_name='order',
            old_name='dt',
            new_name='register_date',
        ),
        migrations.AddField(
            model_name='user',
            name='register_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
