# Generated by Django 4.2.2 on 2023-06-15 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0004_auto_20230606_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='type',
            field=models.CharField(choices=[('shop', 'Магазин'), ('buyer', 'Покупатель')], default='buyer', max_length=5, verbose_name='Тип контакта'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='filename',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Название магазина'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
