# Generated by Django 4.2.2 on 2023-07-14 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0005_alter_contact_type_alter_shop_filename_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ('type',), 'verbose_name': 'Тип контакта пользователя', 'verbose_name_plural': 'Типы контактов пользователей'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Позиция заказа', 'verbose_name_plural': 'Позиции заказов'},
        ),
        migrations.AlterField(
            model_name='contact',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='value',
            field=models.CharField(blank=True, max_length=50, verbose_name='Пояснение'),
        ),
    ]
